name: Build and Push Extract Pipeline

on:
    push:
        paths:
          - 'src/extract/**'
          - 'src/utils/save_to_s3_as_parquet**'
          - 'terraform/extract**'
          - '.github/workflows/extract.yml'

env:
    AWS_REGION: eu-west-2
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    run-checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12.5"
        
            - name: Install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
                pip install -r src/extract/requirements.txt

            - name: Run Bandit Security Checks
              run: |
                source venv/bin/activate
                bandit -r src/extract src/utils/save_to_s3_as_parquet.py
            
            - name: Run Saftey Security Checks
              run: |
                source venv/bin/activate
                safety check --ignore 70612 --file src/extract/requirements.txt
            
            - name: Run Coverage Checks
              run: |
                source venv/bin/activate
                coverage run --source=src/extract,src/utils/save_to_s3_as_parquet.py --omit 'venv/*' -m pytest test/test_extract test/test_utils/test_save_to_s3_as_parquet.py
                coverage report -m

    run-tests:
            runs-on: ubuntu-latest
            env:
                PYTHONPATH: ${{ github.workspace }}
            steps:
                - name: Checkout Repo
                  uses: actions/checkout@v4

                - name: Setup Python
                  uses: actions/setup-python@v4
                  with:
                    python-version: "3.12.5"
        
                - name: Install dependencies
                  run: |
                    python -m venv venv
                    source venv/bin/activate
                    pip install --upgrade pip
                    pip install -r src/extract/requirements.txt 
                
                - name: Run Pytest
                  run: |
                    source venv/bin/activate
                    pytest -v test/test_extract test/test_utils/test_save_to_s3_as_parquet.py
    
    build:
        runs-on: ubuntu-latest
        needs:
            - run-checks
            - run-tests
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            
            - name: Log in to Amazon ECR
              uses: aws-action/amazon-ecr-login@v1
              with:
                region: ${{ env.AWS_REGION }}
                aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

            - name: Build Docker image
              run: |
                docker build -t extract-function -f src/extract/Dockerfile .
            
            - name: Tag Docker image
              run: |
                docker tag extract-function:latest 339712945613.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/short_term_trading_data_pipeline_ecr:extract-latest
        
            - name: Push Docker image
              run: |
                docker push 339712945613.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/short_term_trading_data_pipeline_ecr:extract-latest
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ env.AWS_REGION }}
                aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            
            - name: Terraform Init
              working-directory: terraform/extract
              run: |
                if [ ! -d ".terraform" ]; then
                  terraform init
                else
                  echo "Terraform already initialised"
                fi
            
            - name: Terraform Plan
              working-directory: terraform/extract
              run: terraform plan -var-file="../terraform.tfvars"
      
            - name: Terraform Apply
              working-directory: terraform/extract
              run: terraform apply -var-file="../terraform.tfvars" -auto-approve