name: Build and Push Extract Pipeline

on:
    push:
        branches:
            - main

jobs:
    run-checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12.5"
        
            - name: Install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
                pip install -r src/extract/requirements.txt

            - name: Run Bandit Security Checks
              run: |
                source venv/bin/activate
                bandit -r src/
            
            - name: Run Saftey Security Checks
              run: |
                source venv/bin/activate
                safety check --ignore 70612
            
            - name: Run Coverage Checks
              run: |
                source venv/bin/activate
                coverage run --omit 'venv/*' -m pytest && coverage report -m

    run-tests:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout Repo
                  uses: actions/checkout@v4

                - name: Setup Python
                  uses: actions/setup-python@v4
                  with:
                    python-version: "3.12.5"
        
                - name: Install dependencies
                  run: |
                    python -m venv venv
                    source venv/bin/activate
                    pip install --upgrade pip
                    pip install -r src/extract/requirements.txt 
                
                - name: Run Pytest
                  run: |
                    source venv/bin/activate
                    pytest -v   
    
    build:
        runs-on: ubuntu-latest
        needs:
            - run-checks
            - run-tests
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            
            - name: Log in to Amazon ECR
              id: ecr-login
              uses: aws-action/amazon-ecr-login@v1

            - name: Build Docker image
              run: |
                docker build -t extract-function src/extract
            
            - name: Tag Docker image
              run: |
                docker tag extract-function:latest 339712945613.dkr.ecr.eu-west-2.amazonaws.com/extract-function-repo:latest
        
            - name: Push Docker image
              run: |
                docker push 339712945613.dkr.ecr.eu-west-2.amazonaws.com/extract-function-repo:latest
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: eu-west-2
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
            - name: Terraform Init
              working-directory: terraform
              run: terraform init
            
            - name: Terraform Plan
              working-directory: terraform
              run: terraform plan
      
            - name: Terraform Apply
              working-directory: terraform
              run: terraform apply -auto-approve